#!/bin/bash

function help {
  if [ "$1" ]; then
    >&2 echo "Error: $1"
    >&2 echo ""
  fi
  >&2 echo "Usage: capture command to execute with arguments

Creates hidden file '$DIR/.result.json'.

Example: ./capture aws sts get-caller-identity
"
  exit 1
}


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ -z "$1" ]; then help "no shell command provided."; fi

export AWS_DEFAULT_OUTPUT=json
echo $( $@ ) > "$DIR/.result.json"
cat "$DIR/.result.json"
