#!/bin/bash

# Usage: capture command to execute with arguments
# Example: ./capture aws sts get-caller-identity

if [ -z "$1" ]; then
  2> echo "Error: no shell command provided."
fi

echo $( $@ ) > .result
cat .result
