#!/bin/bash

# Usage: capture command to execute with arguments
# Example: ./capture aws sts get-caller-identity

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ -z "$1" ]; then
  >&2 echo "Error: no shell command provided."
fi

echo $( $@ ) > "$DIR/.result"
cat "$DIR/.result"
