#!/bin/bash

# Usage: extract jqSpecifier
# Example: extract .UserId

if [ -z "$1" ]; then
  >&2 echo "Error: no jq specification provided."
fi

RESULT=$( cat .result | jq -r $@ )
echo $RESULT
>&2 echo $RESULT
